nodeLinker: node-modules
enableGlobalCache: true
nmMode: hardlinks-local

# Force this to be treated as a standalone project
npmRegistryServer: "https://registry.npmjs.org/"

# Disable pnp to ensure compatibility
pnpMode: loose

# Disable workspace features

# Avoid fsevents issue on macOS
supportedArchitectures:
  os: [darwin, linux, win32]
  cpu: [x64, arm64, ia32]
  libc: [glibc, musl]
